name: powernukkit-plugin
main: skillter.Main
version: "1.0.0"
api: ["1.0.13"]
load: POSTWORLD
author: Skillter
description: A test plugin
permissions:
  powernukkitplugin:
    description: Allow players to turn on/off keep experience feature
    default: op

commands:
  powernukkitplugin:
    description: Toggle keep experience feature
    permission: "powernukkitplugin.command"
    usage: |
            /<command>
